### ISSUE TITLE
Why roave/security-advisories dependency?

### ISSUE THREAD

**Issue by Tobion** [better-serializer/better-serializer#2]
Why does the serializer require https://github.com/Roave/SecurityAdvisories ?
The package is for applications and not libraries. And requiring dev-master, prevents people to install better-serializer without changing the minimum stability...

**Comment by Rastusik** [comment]
Hi @Tobion , sorry for the delay. Thank you very much for the feedback, it's much appretiated! I removed roave/security-advisories from composer, so hopefully the library will work for you. Feel free to reopen the issue, if there still is a problem. I'll make a new release after fixing the other issues.
