### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by Tobion** [better-serializer/better-serializer#3]
\BetterSerializer\Flysystem\Plugin\FirstXLines tries to read the file with an absolute path like `C:/Users/...` but flysystem adds a leading backslash which results in the final path `\C:/Users/...` which then does not exist. So flysystem throw the exception `League\Flysystem\FileNotFoundException`.
According to https://github.com/thephpleague/flysystem/issues/739 absolute paths should not be used.

**Comment by Rastusik** [comment]
Thanks for the feedback, I'll try to look at this tomorrow.

**Comment by Rastusik** [comment]
@Tobion please check with https://github.com/better-serializer/better-serializer/commit/a43a7a09b05248bb76c1c2e784dfe5c7e92e58d4 . I'm not owning a windows pc, so it's quite difficult to try to find out what the real error was

**Comment by maks-rafalko** [comment]
@Rastusik you can use https://ci.appveyor.com/ to test on windows

**Comment by Rastusik** [comment]
@borNfreee thanks, I'll give it a try

**Comment by Rastusik** [comment]
now it should be 100% sure that better serializer work on windows
