### ISSUE TITLE
ComplexNested: Unexpected processor instance

### ISSUE THREAD

**Issue by Tobion** [better-serializer/better-serializer#4]
When I try to serialize my data, I get the following exception.

```
RuntimeException: Unexpected processor instance: BetterSerializer\DataBind\Writer\Processor\Cached

vendor\better-serializer\better-serializer\src\BetterSerializer\DataBind\Writer\Processor\ComplexNested.php:95
vendor\better-serializer\better-serializer\src\BetterSerializer\DataBind\Writer\Processor\Object.php:67
vendor\better-serializer\better-serializer\src\BetterSerializer\DataBind\Writer\Processor\Factory\RecursiveProcessorFactory.php:116
...
```

Seems like a cached processor can return another cached processor and that does not work in `ComplexNested::resolveRecursiveProcessors`

**Comment by Rastusik** [comment]
This seems quite strange, could you send your object definition? As a quick workaround - have you tried to disable the cache?

**Comment by Tobion** [comment]
When I disable the file cache, I get the same error. It uses an array cache then anyway right? So how would  that make a difference?

**Comment by Rastusik** [comment]
yeah, you're right, I forgot about the array cache ... could you please send the source code of the class that you are trying to serialize, please? I would add it to the unit tests and fix the issue

**Comment by Tobion** [comment]
I cannot share this code and it's a fairl complex object graph. We're trying to figure out if betterserializer is faster than jms in our case. It's unfortunate it does not seem to work. Maybe we have time to find a minimal reproducer.

**Comment by Rastusik** [comment]
It would be great if you would able to find something reproducible, because I'm 99% sure that JMS will be slower (after I'll publish the fix for this issue).

**Comment by Rastusik** [comment]
@Tobion btw try to use VoidCache in `BetterSerializer\Cache\Factory` - that should disable the cache for sure ... it seems that your problem is related to the cache only, so the serialization should work without it

**Comment by Rastusik** [comment]
@Tobion it would also be helpful if you could send at least a var dump of the $processor which doesn't fulfill the condition which results in the RuntimeException

**Comment by Tobion** [comment]
I'm closing this as we did not pursue this direction.
